"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.addressRouter = exports.authRouter = exports.usersRouter = exports.shippingInfoRouter = exports.productReviewRouter = exports.paymentRouter = exports.orderRouter = exports.orderItemRouter = exports.favouritesRouter = exports.cartItemRouter = exports.cartRouter = exports.addonOptionsRouter = exports.addonsRouter = exports.categoryRouter = exports.productRouter = void 0;
var product_routes_1 = require("./product.routes");
Object.defineProperty(exports, "productRouter", { enumerable: true, get: function () { return __importDefault(product_routes_1).default; } });
var category_routes_1 = require("./category.routes");
Object.defineProperty(exports, "categoryRouter", { enumerable: true, get: function () { return __importDefault(category_routes_1).default; } });
var addons_routes_1 = require("./addons.routes");
Object.defineProperty(exports, "addonsRouter", { enumerable: true, get: function () { return __importDefault(addons_routes_1).default; } });
var addonOptions_routes_1 = require("./addonOptions.routes");
Object.defineProperty(exports, "addonOptionsRouter", { enumerable: true, get: function () { return __importDefault(addonOptions_routes_1).default; } });
var cart_routes_1 = require("./cart.routes");
Object.defineProperty(exports, "cartRouter", { enumerable: true, get: function () { return __importDefault(cart_routes_1).default; } });
var cartItem_routes_1 = require("./cartItem.routes");
Object.defineProperty(exports, "cartItemRouter", { enumerable: true, get: function () { return __importDefault(cartItem_routes_1).default; } });
var favourites_routes_1 = require("./favourites.routes");
Object.defineProperty(exports, "favouritesRouter", { enumerable: true, get: function () { return __importDefault(favourites_routes_1).default; } });
var orderItem_routes_1 = require("./orderItem.routes");
Object.defineProperty(exports, "orderItemRouter", { enumerable: true, get: function () { return __importDefault(orderItem_routes_1).default; } });
var order_routes_1 = require("./order.routes");
Object.defineProperty(exports, "orderRouter", { enumerable: true, get: function () { return __importDefault(order_routes_1).default; } });
var payment_routes_1 = require("./payment.routes");
Object.defineProperty(exports, "paymentRouter", { enumerable: true, get: function () { return __importDefault(payment_routes_1).default; } });
var productReview_routes_1 = require("./productReview.routes");
Object.defineProperty(exports, "productReviewRouter", { enumerable: true, get: function () { return __importDefault(productReview_routes_1).default; } });
var shippingInfo_routes_1 = require("./shippingInfo.routes");
Object.defineProperty(exports, "shippingInfoRouter", { enumerable: true, get: function () { return __importDefault(shippingInfo_routes_1).default; } });
var users_routes_1 = require("./users.routes");
Object.defineProperty(exports, "usersRouter", { enumerable: true, get: function () { return __importDefault(users_routes_1).default; } });
var auth_routes_1 = require("./auth.routes");
Object.defineProperty(exports, "authRouter", { enumerable: true, get: function () { return __importDefault(auth_routes_1).default; } });
var address_routes_1 = require("./address.routes");
Object.defineProperty(exports, "addressRouter", { enumerable: true, get: function () { return __importDefault(address_routes_1).default; } });
